### ISSUE TITLE
How to obtain the charge of each atom of MOFs?

### ISSUE THREAD

**Issue by pincher-chen** [peteboyd/lammps_interface#12]
Hi,

I want to use UFF4MOF to simulate my model, but I found the charges of MOFs are not  assigned by lammps_interface.py.  A method is mentioned  in paper of Journal of Computational Chemistry, Vol. 11, No. 4, 431-439 (1990) . Here, if i get  charges by method of quantum chemistry,  I am wondering how lammps_interface.py writes charges to data file of lammps. Can you give me some tips?

**Comment by askforarun** [comment]
quick and dirty solution: Cut the "Atom section" paste in to matlab as a matrix say A
Open matlab
Charge= [....]
Then A(:,3)=charge;

Elegant solution: grep, bash, awk, sed

**Comment by peteboyd** [comment]
Hi,
If you have partial charges for each atom, you can enter them as a new column in the .cif file as '_atom_type_partial_charge' in the atom block.
