### ISSUE TITLE
Include fix momentum in the in. file

### ISSUE THREAD

**Issue by danieleongari** [peteboyd/lammps_interface#14]
In order to avoid the crystal translating, it is mandatory to null the net transnational momentum during the simulation. 
What about adding it by default or selecting a proper flag?

`
fix 1 all momentum 1 linear 1 1 1 angular
`

REF: https://lammps.sandia.gov/doc/fix_momentum.html

**Comment by peteboyd** [comment]
Daniele, use the LSMO version of lammps interface. It is implemented in that one and has other features you might be interested in. I will add this as default on the public version

**Comment by danieleongari** [comment]
Thanks, it works!
