### ISSUE TITLE
lammps datafile for UFF - redefinition of the unitcell

### ISSUE THREAD

**Issue by sknippen** [peteboyd/lammps_interface#17]
Dear,

Willing to generate the UFF datafile for Lammps for the structure in attachment, I get the message 'bonded atoms (nr) and (nr) are 7.730 Angstroms apart. This probably has something to do with the redefinition of the unitcell to a supercell. Please contact the developers!'

The final files, which I hoped to get, have not been generated and the program hangs. I attached the input structures (pdf and cif, which I had to use in the program) in attachment.  
[problem_uff.zip](https://github.com/peteboyd/lammps_interface/files/3389153/problem_uff.zip)

Remark that the structure consists out of layers, and that inside each layer a compound is used, which has symmetry. For completeness, I attached as well this symmetric part of the compound in one layer (*_ori_cif.zip).
[PR122_ori_cif.zip](https://github.com/peteboyd/lammps_interface/files/3389161/PR122_ori_cif.zip)
 
Can you please have a look at it? 

Thank you!

Stefan

**Comment by ltalirz** [comment]
@peteboyd @danieleongari Is somebody willing to look into this?

**Comment by sknippen** [comment]
(From my side, I am still interested...)

**Comment by peteboyd** [comment]
I'll have a look

**Comment by peteboyd** [comment]
Stefan, I have looked at your cif files and have found the problem. The one titled 'PR122_uff.cif' contains symmetry elements that the lammps-interface code cannot currently process. This is something we should address, and there is another issue that raises this concern (issue #5). 

The one titled 'PR122_try.cif' is P1 symmetry, however there appears to be too many molecules described in the unit cell. If I look at the number of atoms in the small bounding box, I count 42. However in your file there are 504! It is likely that whatever software you were using provided replicated molecules from a supercell.  One of the cif processing steps the code will do is try to fit all the atoms within the unit cell, prior to computing bonding. I'm a little surprised I didn't implement an atom overlap check at this stage, but I've done so now and will exit with a message telling the user to check their system before proceeding.

I've provided a modified unit cell for you, that only contains 42 atoms and works with the lammps-interface code.
[PR122_unit.txt](https://github.com/peteboyd/lammps_interface/files/3537175/PR122_unit.txt)
(just change .txt to .cif)

**Comment by sknippen** [comment]
Dear Pete,

Thank you!

I understand now that the Lammps-interface requires for the triclinic case one unit cell, which helps me a lot. 

If I may, the point where I am still a bit puzzled now is how the program determines on its own the dimension of the final slab. In the code, I find the reconversion of the a,b,c-alpha,beta,gamma unit cell to lx,xy,... Are then the final lx, ly and lz of the supercell calculated with respect to a half-cell cutoff? If I would like to have a much larger slab, how should that be said to the lammps_interface.py?  

Thank you again for the clarifications and help!

Stefan

**Comment by sknippen** [comment]
Indeed, thanks!

Op ma 26 aug. 2019 om 19:33 schreef Peter Boyd <notifications@github.com>:
