### ISSUE TITLE
How to execute the main script

### ISSUE THREAD

**Issue by paulmeza** [peteboyd/lammps_interface#2]
Dear Peter

Could you provide a brief description about how to execute the lammps_main.py

I appreciate your comments

**Comment by peteboyd** [comment]
Hi sorry, I should really put a tutorial somewhere.
Currently the program works as,
`lammps_main.py [options] cif_file.cif`
the options are presented to you if you type
`lammps_main.py --help`
If you just put
`lammps_main.py cif_file.cif`
it will default to the UFF parameters and create LAMMPS files which will ultimately do nothing when you run LAMMPS. You can add your own lammps directives in the `in.[cif_file]` file that is produced.

Let me know if you have any problems!
Pete

**Comment by ltalirz** [comment]
The way to call lammps-interface has changed a bit now - after installation, you can now simply use `lammps-interface` anywhere and it should work.

Closing this.
