### ISSUE TITLE
Issue with the networkx newer than 2.3

### ISSUE THREAD

**Issue by pzarabadip** [peteboyd/lammps_interface#24]
Hi, 
I just realized the `lammps_interface` is not working with `networkx` `version 2.40` which has been installed as the latest version. I had to downgrade to `version 2.30` for having the code working. I still did not fully investigate the source of issue but I think it would be related to the removal of depreciated  functions in the latest version:
https://networkx.github.io/documentation/stable/release/release_2.4.html

Thus, I think a quick fix for now would be putting a limitation on the version of `networkx`. 
My best,
Pezhman

**Comment by peteboyd** [comment]
Hi Pezhman,
Many thanks for this! I will try to have it work with newer versions of networkx ASAP.
Best,
Pete

**Comment by ltalirz** [comment]
@peteboyd  up to you - otherwise, it's also very easy to make a 1.1.2 release that simply has `networkx<2.4` dependency.

**Comment by peteboyd** [comment]
Fixed with commit 371d5d93110b349d51b5d7bfb7ef2bcc89752b7b
