### ISSUE TITLE
After the installation lammps-interface is not recognised as a command 

### ISSUE THREAD

**Issue by zoolflix** [peteboyd/lammps_interface#29]
C:\WINDOWS\system32>lammps-interface --help
'lammps-interface' is not recognized as an internal or external command,
operable program or batch file.

**Comment by ltalirz** [comment]
thanks for reporting, I've just added installation on windows to the continuous integration tests and was able to reproduce your issue:
https://github.com/ltalirz/lammps_interface/runs/618074170#step:5:6

I've fixed the problem by moving the `lammps-interface` script to a `console_scripts` entry point in PR #32 , which I've just merged into the `master` branch.
https://github.com/peteboyd/lammps_interface/pull/32/checks?check_run_id=618096243#step:5:1

You could try installing the latest master branch using something like
```
pip install git+https://github.com/peteboyd/lammps_interface
```

**Comment by zoolflix** [comment]
Thanks for fixing the bug and for the very fast feedback ! It works perfect now :D Merci !!!
