### ISSUE TITLE
InputHandler.py error

### ISSUE THREAD

**Issue by zidane611** [peteboyd/lammps_interface#3]
Hi,

When I run the program in the Linux system with Anaconda python 2.7. I got an error, 
"./subprocess.py", line 1335, in _execute_child raise child_exception
OSError: [Errno 2] No such file or directory. 

This error is coming from line 10 of InputHandler.py file.
Do you have any ideas about this?

Thanks a lot,
Zesheng

**Comment by peteboyd** [comment]
Hey, I think this was caused because you downloaded the .zip file of the source code instead of 'git clone'ing it to your local computer. I've added a fix that should make it work for you. Please re-open if the problem persists.
Thanks for posting the issue!
Pete
