### ISSUE TITLE
Invalid atom ID in Dihedrals section of data file

### ISSUE THREAD

**Issue by tawe141** [peteboyd/lammps_interface#34]
Maybe this isn't the right place to post this, but I figured I would give it a shot. 

LAMMPS throws the error in the title for a structure I'm working on. I've been able to verify in the generated data file that each atom ID in the Dihedrals section corresponds to an atom in the Atoms section, so I'm at a loss for why LAMMPS throws this error. The structure itself is unphysical in that some of the atoms are too close to each other, so I'm not surprised there would be difficulties, but it seems like a strange error to have when all of the atom IDs match. Could someone advise on how to proceed?

**Comment by peteboyd** [comment]
@tawe141 I think LAMMPS throws this error when the system 'explodes'. As you say the system is unphysical, but without further information I can't be sure. You might want to visualize the trajectory to get an idea of what is going on.
You might want to try adjusting the initial positions of the atoms so there isn't as much repulsive energy at the beginning of the simulation.
