### ISSUE TITLE
cut_molecule

### ISSUE THREAD

**Issue by michelleernst** [peteboyd/lammps_interface#40]
Dear all, 
I was trying to use the lammps interface with the test cif IRMOF-1.cif you provide in the test folder (as well as with some other cifs). For all the tested cif files I get this error message: 
_main.py", line 1532, in cut_molecule
    mgraph.coordinates = self.graph.coordinates[indices,:].copy()
TypeError: 'NoneType' object is not subscriptable
I would be very glad for help to fix this issue.
Kind regards,
Michelle Ernst

**Comment by ltalirz** [comment]
Thanks for the report @michelleernst - this really highlights the fact that we absolutely [should be adding automatic tests](https://github.com/peteboyd/lammps_interface/issues/30), which would prevent such failures on the test structures in the repository.

I've just added a pull request that starts running some of those and I'm able to reproduce your issue.
Interestingly, it seems to depend on the python version - in a fresh local python 3.6 environment, the code runs fine, while in a python 3.8 environment it doesn't.

**Comment by ltalirz** [comment]
@peteboyd It seems to me there is some remaining issue with the upgrade to networkx 2.4

Would you mind having a look into this?

@michelleernst In the meanwhile, you should be able to use the code in a python 3.6 environment (which you can create, for example, using conda)

**Comment by peteboyd** [comment]
It was an issue with the module time. A while ago had merged a pull request that printed the time for computing each force field element in a cif file. It was calling `time.clock()` which is apparently deprecated.

**Comment by ltalirz** [comment]
@michelleernst As demonstrated by the passing tests in https://github.com/peteboyd/lammps_interface/pull/41 , the current master branch of the repository should work.
Once the PR is merged, I will make a 1.4.0 release on PyPI as well.

**Comment by ltalirz** [comment]
I've just pushed out v0.2.0 to pypi. Should be available in a few minutes.
