### ISSUE TITLE
self diffusion for UMCM-1 with 1-phenylamine

### ISSUE THREAD

**Issue by jiamingl98** [peteboyd/lammps_interface#52]
Hi,
I have a problem to combine dihedral_style and improper_style for both MOF and guest molecule. I want to calculate the mean square displacement for 1-phenylamine in UMCM-1. However, the bond style, angle style, dihedral style, and improper style for MOF generated by lammps-interface is different with 1-phenylamine generated by LigParGen (OPLS-AA force field).

Input file for MOF:
units           real
atom_style      full
boundary        p p p

pair_style      lj/cut/coul/long 12.500
bond_style      harmonic
angle_style     hybrid fourier cosine/periodic
dihedral_style  harmonic
improper_style  fourier
kspace_style    ewald 0.000001

special_bonds   lj/coul 0.0 0.0 1.0
dielectric      1.0
pair_modify     tail yes mix arithmetic
box tilt        large
read_data       data.UMCM1

Input file for 1-phenyamine by Ligpargen server:
units real
atom_style full

dimension 3
boundary p p p

pair_style lj/cut/coul/cut 20.0 20.0
pair_modify mix geometric

bond_style harmonic 
angle_style harmonic
dihedral_style opls 
improper_style cvff
special_bonds lj/coul 0.0 0.0 0.5 

read_data 1phenylamine.lmp

They have different angle_style, dihedral_style, and improper_style. How can I combine my guest molecule and MOF to simulate the MSD with different angle, dihedral, and improper styles? In addition, can I change the improper style for MOF other than fourier because it require user-misc package but our HPC do not install it?

Thanks.

**Comment by peteboyd** [comment]
I think the issues you bring up are not related to the code we distribute, but with your understanding of LAMMPS. I would reference the lammps manual `https://docs.lammps.org/Manual.html` to answer how to combine dihedral styles. To solve your problem with the HPC I would suggest either contacting their IT people with your request, or installing LAMMPS in your local directory on the HPC. Failing that you can just install LAMMPS on your local computer and run the simulation.
I'm closing this but if I've misinterpreted your issue and it actually is related to lammps_interface, please re-open.

**Comment by jiamingl98** [comment]
Can I combine MOF with guest molecule to generate one lammps input file by using lammps-interface?
