### ISSUE TITLE
Typo in lammps_main.py response = input("Would you like to replicate molceule %i with atoms (%s) in the supercell? [y/n]: "%

### ISSUE THREAD

**Issue by jaharvey8** [peteboyd/lammps_interface#65]
Line 533 in lammps_main.py prints a response to user and there is a typo in the outputted response

response = input("Would you like to replicate molceule %i with atoms (%s) in the supercell? [y/n]: "%

change "molceule" to "molecule"

**Comment by ltalirz** [comment]
fixed in #66
